apiVersion: v1
kind: Service
metadata:
  name: mura-service
spec:
  type: {{ .Values.service.type }}
  selector:
    app: mura-app
  ports:
  - port: {{ .Values.service.port }}
    targetPort: app-port
    protocol: TCP
